# logger/config.yaml
version: 1
disable_existing_loggers: false

formatters:
  colorized:
    (): infra.logger.formatters.ColorizedFormatter  # Полный путь к классу
    format: '%(levelprefix)s %(name)-35s %(message)s'
    datefmt: '%H:%M:%S'
  detailed:
    format: '%(levelname)-8s %(asctime)s.%(msecs)03d %(name)-35s %(module)s:%(lineno)d - %(message)s'
    datefmt: '%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colorized
    stream: ext://sys.stdout


loggers:
  # lib
  # project
  __main__:
    level: INFO
    handlers: [ console ]
    propagate: false
  bot:
    level: DEBUG
    handlers: [ console ]
    propagate: false
  entity:
    level: DEBUG
    handlers: [ console ]
    propagate: false
  infra.db:
    level: DEBUG
    handlers: [ console ]
    propagate: false


root:
  level: WARNING
  handlers: [ console ]
